export default defineAppConfig({
  pages: [
    "pages/home/index",
    "pages/community/index",
    "pages/community-detail/index",
    "pages/community-publish/index",
    "pages/login/index",
    "pages/mine/index",
    "pages/lucky/index",
    "pages/chat/index",
    "pages/index/index",
    "pages/activity-lottery/index",
    "pages/activity-mine/index",
    "pages/activity-invite/index",
    "pages/user-details/index",
    "pages/mall/index",
    "pages/mask-list/index",
    "pages/my-order/index",
    "pages/msg-list/index",
    "pages/circle-details/index",
    "pages/common-search/index",
    "pages/circle-create/index",
    "pages/circle-create/intro",
    "pages/msg-list/collect/index",
    "pages/msg-list/comment/index",
    "pages/msg-list/follow/index",
    "pages/search/index",
    "pages/all-circles/index",
    "pages/all-topic/index",
    "pages/leader-board/index",
    "pages/new-chat/index",
    "pages/works-management/index",
    "pages/report/index",
    "pages/pick-user/index",
    "pages/application-management/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#fff",
    navigationBarTitleText: "WeChat",
    navigationBarTextStyle: "black",
  },
});
